# Generated by Django 3.2.6 on 2021-09-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_alter_customer_contactnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='BookTitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='Category',
            field=models.CharField(max_length=50),
        ),
    ]
