# Generated by Django 3.2.6 on 2021-10-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_auto_20211005_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
