# Generated by Django 3.2.6 on 2021-10-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0008_delete_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
