# Generated by Django 3.2.6 on 2021-10-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0009_auto_20211014_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='repassword',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
