# Generated by Django 3.2.6 on 2021-10-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0011_auto_20211017_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='admin',
            name='Username',
            field=models.CharField(max_length=50),
        ),
    ]
